### ISSUE TITLE
localStorage is still shared among sandboxes

### ISSUE THREAD

**Issue by temsa** [bakulf/priv8#16]
you can check using different accounts on http://allocab.com

**Comment by bakulf** [comment]
Can you tell me more about how to test it?

**Comment by temsa** [comment]
1. create a sandbox
2. create one account on allocab.com in this sandbox and/or log in (you might need to start creating a trip up to the second step, I did not check)
3. create another sandbox : you are still logged in.

session data is stored in the localStorage on this website, it seems to explain the issue, at least partially, because something is still weird : 
- SESSION_AUTH key stays in the localStorage from sandbox to sandbox
- FLASH_MESSAGE and FLASH_FORM_MESSAGE keys do not stay (yet their last update date is 01/01/1970)

**Comment by temsa** [comment]
@bakulf any idea ? :°)

**Comment by bakulf** [comment]
I cannot reproduce it. I had 2 sandboxes and I'm fully logged in 1 and anonymous in the second one.

**Comment by MuhPirat** [comment]
Same here, 
I cant reproduce the error to.

**Comment by temsa** [comment]
Ok, could not reproduce until I switched back to e10s mode.

When recovering tabs in e10s mode, already opened sandbox tab seems to still apply, yet localStorage is shared (maybe cookies too).

**Comment by temsa** [comment]
@bakulf should be fixed by fixing #5 / #18
