### ISSUE TITLE
Which elements are sandboxed exactly?

### ISSUE THREAD

**Issue by lliseil** [bakulf/priv8#22]
I'd like if you could detail which elements does priv8 sandoxes than eg Steve Tine's CookieSwap doesn't? Case study: Google related services.
Am asking as the description is nice while a bit vague

    a Firefox addon that uses part of the security model of Firefox OS to create sandboxed tabs. Each sandbox is a completely separated world: it doesn't share cookies, storage, and a lots of other stuff 

Nice to have you on Github.

**Comment by bakulf** [comment]
What priv8 sandboxes (using appIds) is: cookies, any kind of storage (localStorage, IDB, etc), etags.
More information can be read from this page:

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Security/Application_security#Web_App_Sandbox
