### ISSUE TITLE
Stopped working in Firefox 44

### ISSUE THREAD

**Issue by fdegrave** [bakulf/priv8#25]
Hi,

Since last Firefox update (44), the addon stopped working. The icon in the toolbar has disappeared, the only sign of Priv8 being installed is in the contextual menu when right-clicking a tab. And it doesn't work that way either...

I tried on a fresh Firefox profile but same behavior.

Cheers,

François

**Comment by clriis** [comment]
Yes. Same thing in Cyberfox. It's really disappointing as this is one of my favourite Add-ons.

**Comment by bakulf** [comment]
Yeah, something breaks in the latest firefox.
I'm working on it in order to fix it soon.

**Comment by bakulf** [comment]
Actually, I cannot reproduce this issue. Do you have any stderr log to share?

**Comment by fdegrave** [comment]
Yes, when I run firefox I get the following console messages:

`console.error: priv8: 
  Message: ReferenceError: can't access lexical declaration `button' before initialization
  Stack:
    refreshButtonIcons@resource://id-at-baku-dot-priv8/priv8/lib/main.js:53:1
refreshWindows@resource://id-at-baku-dot-priv8/priv8/lib/main.js:46:9
@resource://id-at-baku-dot-priv8/priv8/lib/main.js:82:1
CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18
run@resource://gre/modules/commonjs/sdk/addon/runner.js:147:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
Handler.prototype.process@resource://gre/modules/Promise-backend.js:934:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:747:1

*************************
A coding exception was thrown in a Promise resolution callback.
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full message: ReferenceError: can't access lexical declaration `button' before initialization
Full stack: refreshButtonIcons@resource://id-at-baku-dot-priv8/priv8/lib/main.js:53:1
refreshWindows@resource://id-at-baku-dot-priv8/priv8/lib/main.js:46:9
@resource://id-at-baku-dot-priv8/priv8/lib/main.js:82:1
CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18
run@resource://gre/modules/commonjs/sdk/addon/runner.js:147:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
Handler.prototype.process@resource://gre/modules/Promise-backend.js:934:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:747:1

*************************
console.error: priv8: 
  Message: ReferenceError: can't access lexical declaration `button' before initialization
  Stack:
    refreshButtonIcons@resource://id-at-baku-dot-priv8/priv8/lib/main.js:53:1
refreshWindows@resource://id-at-baku-dot-priv8/priv8/lib/main.js:46:9
@resource://id-at-baku-dot-priv8/priv8/lib/main.js:82:1
CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18
run@resource://gre/modules/commonjs/sdk/addon/runner.js:147:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
Handler.prototype.process@resource://gre/modules/Promise-backend.js:934:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:747:1`

**Comment by bakulf** [comment]
Thanks for this! Problem solved in the latest 2 commits.
A new version of priv8 is in the addon review queue.

**Comment by clriis** [comment]
It's working now. Thanks a lot!
