### ISSUE TITLE
Doesn't work with FF 49.0.2 (link to #31 )

### ISSUE THREAD

**Issue by darkpisto** [bakulf/priv8#33]
Same problem in :  Doesn't work with FF 49.0.1 #31 

The button disappeared again, and we can't choose a context when we "right click" on a tab.

**Comment by bakulf** [comment]
Can you tell me exactly how to reproduce this issue?
Can you also run firefox in a terminal (I don't know which OS you use, maybe this could be tricky) and send me the output in case some errors are shown?

**Comment by darkpisto** [comment]
(Sorry, I don't speak english very well)

I use Windows 7 but I don't know how to run firefox in a terminal.

And I don't know how to reproduce : I only run firefox like usually, but sometimes the button doesn't exist anymore, and do a right click on a tab don't show the priv8 menu. (but extension priv8 is active and seems properly installed).

If I uninstall and reinstall priv8 : the problem continue.
If I completely remove the extension (I must go in config:about to remove all mention of "priv8") and reinstall, sometimes priv8 work again (until the next closure and start of the browser).

**Comment by darkpisto** [comment]
I guess the problem is not with priv8 : I have 2 others addons with the same problem ... and it's partially solved (when I restart firefox, sometimes the 3 addons disappeared and sometimes they come back).

I close the issue, and thanks to your great work :)
