### ISSUE TITLE
cookies not isolated?

### ISSUE THREAD

**Issue by pysli** [bakulf/priv8#35]
Currently I see that web storage is registered under sandbox id*, ex. "1001" instead of site url but cookies aren't - they're registered like normal site cookies under "example.com" so when I'm logged in sandbox then I'm logged in without sandbox at same time and vice versa. After I delete cookies for example.com, cookies from sandbox are also deleted.

*numeration is somewhat different. Sandbox id's are numerated as 1001,1002,1003...but web storage is numerated as 1001,2001,3001 which is confusing.

Firefox 50, Priv8 1.6, electrolysis disabled.

**Comment by pysli** [comment]
Any ideas about this? Is it reproducible?

**Comment by bakulf** [comment]
I cannot reproduce it. I guess this problem is already fixed. And I suspect that happen because version 0.1.5 was a mess: it broke the say the cookies were managed.

**Comment by pysli** [comment]
Hmm...I've only used version 1.6...
So the cookies are registered under sandbox id i.e. 1001 and not  facebook.com for you?
