### ISSUE TITLE
e10s is not supported

### ISSUE THREAD

**Issue by bakulf** [bakulf/priv8#5]

**Comment by temsa** [comment]
yep, fixing this would be great for the future :+1:

**Comment by lliseil** [comment]
Ah ok. Shouldn't the add-on check for this when installing on e10s Electrolys?

Priv8 installed like a breeze on my Fx 46.0a2 (2016-01-27) webdev profile. I then created Priv8 profiles, opened one... to discover the cookies were shared as usual, grumpf! ;)

**Comment by bakulf** [comment]
Version 0.2.0 (in review) supports e10s.
