### ISSUE TITLE
Tab text color is not updated when you change the sandbox color while a tab is open

### ISSUE THREAD

**Issue by JohanLorenzo** [bakulf/priv8#7]
## Steps to reproduce
1. Open a new tab
2. Sandbox it => See the border and the text color
3. Open the priv8 manager
4. Change the color of the sandbox

## Expected result
The text color should change each time you select a new color.

## Actual result
The text color is never updated. When you switch to the tap open in step 1, the border has the new color but not the text.

**Comment by bakulf** [comment]
fix committed
