### ISSUE TITLE
The border can get 2 colors if you quit Firefox while a sandboxed tab is displayed

### ISSUE THREAD

**Issue by JohanLorenzo** [bakulf/priv8#8]
## STR
1. Open a sandboxed tab 
2. Open a second tab but in another sandbox.
3. Quit Firefox (like with Ctrl+Q)
4. Reopen it
5. Switch to the first sandboxed tab

## Actual result
Both colors are displayed on the border, like here:
![priv8-bug 8](https://cloud.githubusercontent.com/assets/5907366/5613353/586cdb42-94e3-11e4-9be0-6a956d63704a.png)

If you go back to the second sandboxed tab, the border will be thicker. If you open a new sandboxed tab, the new one only will appear like expected.

**Comment by bakulf** [comment]
Problem fixed in the latest commit.
